const React = window.React;
import Icon from './Icon.js';
export default function About() {
    return React.createElement("section", { className: "about section", id: "sobre", "aria-labelledby": "about-title" },
        React.createElement("div", { className: "container about__layout" },
            React.createElement("div", { className: "about__intro reveal" },
                React.createElement("p", { className: "eyebrow eyebrow--blue" },
                    React.createElement("span", { className: "eyebrow__square" }),
                    " SOBRE A VSM"),
                React.createElement("h2", { className: "section-heading", id: "about-title" },
                    "H\u00E1 d\u00E9cadas, ",
                    React.createElement("br", null),
                    "\u00E0 frente do ",
                    React.createElement("em", null, "pr\u00F3ximo passo.")),
                React.createElement("div", { className: "about__signature" },
                    React.createElement("span", null, "DESDE"),
                    React.createElement("strong", null, "1992"),
                    React.createElement("span", null, "ASSIS \u2022 SP"))),
            React.createElement("div", { className: "about__details reveal" },
                React.createElement("p", { className: "about__lead" }, "A tecnologia evolui. A forma de cuidar do seu neg\u00F3cio tamb\u00E9m."),
                React.createElement("p", null, "Fundada em Assis, no interior de S\u00E3o Paulo, a VSM Inform\u00E1tica desenvolve softwares especializados para farm\u00E1cias, drogarias e farm\u00E1cias de manipula\u00E7\u00E3o."),
                React.createElement("p", null, "Com atua\u00E7\u00E3o nacional, conecta diferentes etapas da gest\u00E3o em um ecossistema que transforma informa\u00E7\u00E3o em organiza\u00E7\u00E3o, agilidade e capacidade de decis\u00E3o."),
                React.createElement("a", { className: "text-link", href: "https://www.vsm.com.br/", target: "_blank", rel: "noopener noreferrer" },
                    "Conhe\u00E7a a VSM oficial ",
                    React.createElement(Icon, { name: "arrow-up-right", size: 18 })))),
        React.createElement("div", { className: "container about__numbers reveal" },
            React.createElement("div", { className: "about-number" },
                React.createElement("strong", null,
                    "30",
                    React.createElement("span", null, "+")),
                React.createElement("span", null, "ANOS DE ATUA\u00C7\u00C3O")),
            React.createElement("div", { className: "about-number" },
                React.createElement("strong", null,
                    "3",
                    React.createElement("span", null, "mil+")),
                React.createElement("span", null, "CLIENTES ATENDIDOS")),
            React.createElement("div", { className: "about-number" },
                React.createElement("strong", null,
                    React.createElement(Icon, { name: "globe", size: 44 })),
                React.createElement("span", null, "PRESEN\u00C7A NACIONAL")),
            React.createElement("div", { className: "about__numbers-caption" }, "Experi\u00EAncia constru\u00EDda com tecnologia, proximidade e evolu\u00E7\u00E3o constante.")));
}
