const React = window.React;
import Brand from './Brand.js';
import Icon from './Icon.js';
export default function Footer() {
    return React.createElement("footer", { className: "footer" },
        React.createElement("div", { className: "container" },
            React.createElement("div", { className: "footer__grid" },
                React.createElement("div", { className: "footer__brand" },
                    React.createElement("a", { href: "#inicio", "aria-label": "Voltar ao in\u00EDcio" },
                        React.createElement(Brand, { footer: true })),
                    React.createElement("p", null, "Solu\u00E7\u00F5es tecnol\u00F3gicas para conectar opera\u00E7\u00F5es, organizar informa\u00E7\u00F5es e transformar a gest\u00E3o do varejo farmac\u00EAutico."),
                    React.createElement("div", { className: "footer__location" },
                        React.createElement(Icon, { name: "map-pin", size: 16 }),
                        " Assis, S\u00E3o Paulo \u2022 Brasil")),
                React.createElement("div", { className: "footer__column" },
                    React.createElement("h3", null, "EXPLORAR"),
                    React.createElement("a", { href: "#sobre" }, "Sobre a VSM"),
                    React.createElement("a", { href: "#solucoes" }, "Solu\u00E7\u00F5es"),
                    React.createElement("a", { href: "#tecnologia" }, "Tecnologia"),
                    React.createElement("a", { href: "#diferenciais" }, "Diferenciais"),
                    React.createElement("a", { href: "#faq" }, "Perguntas frequentes")),
                React.createElement("div", { className: "footer__column" },
                    React.createElement("h3", null, "LINKS OFICIAIS"),
                    React.createElement("a", { href: "https://www.vsm.com.br/", target: "_blank", rel: "noopener noreferrer" },
                        "Site da VSM ",
                        React.createElement(Icon, { name: "external", size: 13 })),
                    React.createElement("a", { href: "https://www.vsm.com.br/ourofarma/", target: "_blank", rel: "noopener noreferrer" },
                        "OuroFarma ",
                        React.createElement(Icon, { name: "external", size: 13 })),
                    React.createElement("a", { href: "https://www.vsm.com.br/ouroformulas/", target: "_blank", rel: "noopener noreferrer" },
                        "OuroF\u00F3rmulas ",
                        React.createElement(Icon, { name: "external", size: 13 })),
                    React.createElement("a", { href: "https://www.vsm.com.br/perguntas-frequentes/", target: "_blank", rel: "noopener noreferrer" },
                        "Central de d\u00FAvidas ",
                        React.createElement(Icon, { name: "external", size: 13 }))),
                React.createElement("div", { className: "footer__back" },
                    React.createElement("a", { href: "#inicio", "aria-label": "Voltar ao topo" },
                        React.createElement(Icon, { name: "arrow-up-right", size: 23 })),
                    React.createElement("span", null, "BACK TO TOP"))),
            React.createElement("div", { className: "footer__bottom" },
                React.createElement("span", null,
                    "\u00A9 ",
                    new Date().getFullYear(),
                    " \u2022 ESTUDO DE INTERFACE VSM"),
                React.createElement("span", null,
                    "Conceito demonstrativo independente. ",
                    React.createElement("strong", null, "N\u00E3o \u00E9 um site oficial da VSM Inform\u00E1tica.")))));
}
