const React = window.React;
import Icon from './Icon.js';
const activity = [34, 46, 37, 59, 53, 69, 62, 74, 66, 86, 72, 94];
export default function HeroVisual() {
    return React.createElement("div", { className: "hero-stage", "aria-label": "Ilustra\u00E7\u00E3o de um painel de gest\u00E3o digital com dados demonstrativos" },
        React.createElement("div", { className: "hero-stage__orbit hero-stage__orbit--one", "aria-hidden": "true" }),
        React.createElement("div", { className: "hero-stage__orbit hero-stage__orbit--two", "aria-hidden": "true" }),
        React.createElement("div", { className: "float-node float-node--top" },
            React.createElement(Icon, { name: "database", size: 18 }),
            React.createElement("span", null, "Dados integrados"),
            React.createElement("span", { className: "float-node__live" })),
        React.createElement("div", { className: "dashboard-shell" },
            React.createElement("div", { className: "dashboard-shell__top" },
                React.createElement("div", { className: "dashboard-shell__dots" },
                    React.createElement("i", null),
                    React.createElement("i", null),
                    React.createElement("i", null)),
                React.createElement("span", null, "VSM / ECOSSISTEMA"),
                React.createElement("span", { className: "dashboard-shell__dot" })),
            React.createElement("div", { className: "dashboard-shell__body" },
                React.createElement("div", { className: "dash-sidebar", "aria-hidden": "true" },
                    React.createElement("div", { className: "dash-sidebar__logo" }, "V"),
                    React.createElement("span", { className: "dash-sidebar__active" },
                        React.createElement(Icon, { name: "layout", size: 17 })),
                    React.createElement("span", null,
                        React.createElement(Icon, { name: "chart", size: 17 })),
                    React.createElement("span", null,
                        React.createElement(Icon, { name: "layers", size: 17 })),
                    React.createElement("span", null,
                        React.createElement(Icon, { name: "users", size: 17 })),
                    React.createElement("span", { className: "dash-sidebar__bottom" },
                        React.createElement(Icon, { name: "command", size: 17 }))),
                React.createElement("div", { className: "dashboard-content" },
                    React.createElement("div", { className: "dashboard-content__heading" },
                        React.createElement("div", null,
                            React.createElement("span", { className: "dash-kicker" }, "VIS\u00C3O GERAL"),
                            React.createElement("h3", null,
                                "Seu neg\u00F3cio em foco",
                                React.createElement("span", null, "."))),
                        React.createElement("div", { className: "dash-date" },
                            "Vis\u00E3o demonstrativa ",
                            React.createElement(Icon, { name: "chevron-down", size: 13 }))),
                    React.createElement("div", { className: "dash-stats" },
                        React.createElement("div", { className: "dash-stat" },
                            React.createElement("span", null, "UNIDADES"),
                            React.createElement("strong", null, "04"),
                            React.createElement("small", null,
                                React.createElement("span", { className: "stat-dot" }),
                                " Conectadas")),
                        React.createElement("div", { className: "dash-stat" },
                            React.createElement("span", null, "OPERA\u00C7\u00D5ES"),
                            React.createElement("strong", null, "12,8k"),
                            React.createElement("small", null, "Dados de exemplo")),
                        React.createElement("div", { className: "dash-stat" },
                            React.createElement("span", null, "INTEGRA\u00C7\u00D5ES"),
                            React.createElement("strong", null, "08"),
                            React.createElement("small", null,
                                React.createElement("span", { className: "stat-dot" }),
                                " Em destaque"))),
                    React.createElement("div", { className: "dash-chart" },
                        React.createElement("div", { className: "dash-chart__heading" },
                            React.createElement("span", null, "Atividade da opera\u00E7\u00E3o"),
                            React.createElement("span", { className: "dash-chart__tag" }, "EXEMPLO")),
                        React.createElement("div", { className: "dash-chart__plot" },
                            React.createElement("div", { className: "dash-chart__grid" }),
                            React.createElement("div", { className: "dash-chart__bars" }, activity.map((v, i) => React.createElement("span", { key: i, style: { height: `${v}%` }, className: i === 9 ? 'is-highlighted' : '' })))),
                        React.createElement("div", { className: "dash-chart__months" },
                            React.createElement("span", null, "JAN"),
                            React.createElement("span", null, "FEV"),
                            React.createElement("span", null, "MAR"),
                            React.createElement("span", null, "ABR"),
                            React.createElement("span", null, "MAI"),
                            React.createElement("span", null, "JUN"))),
                    React.createElement("div", { className: "dash-bottom" },
                        React.createElement("span", null,
                            React.createElement(Icon, { name: "activity", size: 13 }),
                            " Fluxo cont\u00EDnuo"),
                        React.createElement("span", null,
                            React.createElement("span", { className: "stat-dot" }),
                            " Ecossistema conectado"))))),
        React.createElement("div", { className: "float-node float-node--bottom" },
            React.createElement("span", { className: "float-node__icon" },
                React.createElement(Icon, { name: "check", size: 16 })),
            React.createElement("span", null,
                React.createElement("strong", null, "Sistemas conectados"),
                React.createElement("small", null, "Uma opera\u00E7\u00E3o mais inteligente"))),
        React.createElement("div", { className: "hero-stage__cross hero-stage__cross--a", "aria-hidden": "true" }, "+"),
        React.createElement("div", { className: "hero-stage__cross hero-stage__cross--b", "aria-hidden": "true" }, "+"));
}
