const React = window.React;
import Icon from './Icon.js';
import HeroVisual from './HeroVisual.js';
export default function Hero() {
    return React.createElement("section", { className: "hero", id: "inicio", "aria-labelledby": "hero-title" },
        React.createElement("div", { className: "hero__mesh", "aria-hidden": "true" }),
        React.createElement("div", { className: "hero__flare", "aria-hidden": "true" }),
        React.createElement("div", { className: "container hero__layout" },
            React.createElement("div", { className: "hero__copy" },
                React.createElement("div", { className: "eyebrow eyebrow--hero" },
                    React.createElement("span", { className: "eyebrow__line" }),
                    " SOFTWARE \u2022 DADOS \u2022 INTEGRA\u00C7\u00C3O"),
                React.createElement("h1", { id: "hero-title" },
                    "Tecnologia que ",
                    React.createElement("span", null, "conecta."),
                    React.createElement("br", null),
                    "Intelig\u00EAncia que ",
                    React.createElement("em", null, "transforma.")),
                React.createElement("p", null, "Um ecossistema de solu\u00E7\u00F5es digitais para simplificar a gest\u00E3o, integrar opera\u00E7\u00F5es e impulsionar o futuro do varejo farmac\u00EAutico."),
                React.createElement("div", { className: "hero__actions" },
                    React.createElement("a", { href: "#solucoes", className: "btn btn--red" },
                        "Conhe\u00E7a nossas solu\u00E7\u00F5es ",
                        React.createElement(Icon, { name: "arrow-up-right", size: 18 })),
                    React.createElement("a", { href: "#sobre", className: "btn btn--outline" },
                        "Descubra a VSM ",
                        React.createElement(Icon, { name: "arrow-right", size: 18 }))),
                React.createElement("div", { className: "hero__trust" },
                    React.createElement("span", { className: "hero__trust-line" }),
                    React.createElement("span", null,
                        React.createElement("strong", null, "+30 anos"),
                        " de experi\u00EAncia"),
                    React.createElement("span", { className: "hero__trust-divider" }),
                    React.createElement("span", null,
                        React.createElement("strong", null, "+3 mil"),
                        " clientes"),
                    React.createElement("span", { className: "hero__trust-divider" }),
                    React.createElement("span", null,
                        React.createElement("strong", null, "Todo o Brasil")))),
            React.createElement(HeroVisual, null)),
        React.createElement("div", { className: "hero__bottom container" },
            React.createElement("span", null,
                React.createElement(Icon, { name: "mouse", size: 16 }),
                " EXPLORE O ECOSSISTEMA"),
            React.createElement("span", null, "01 / 06 \u2014 CONHE\u00C7A A VSM")));
}
