const React = window.React;
import { solutions } from '../data/content.js';
import Icon from './Icon.js';
export default function Solutions() {
    return React.createElement("section", { className: "solutions section", id: "solucoes", "aria-labelledby": "solutions-title" },
        React.createElement("div", { className: "container" },
            React.createElement("div", { className: "section-top reveal" },
                React.createElement("div", null,
                    React.createElement("p", { className: "eyebrow eyebrow--blue" },
                        React.createElement("span", { className: "eyebrow__square" }),
                        " NOSSO ECOSSISTEMA"),
                    React.createElement("h2", { className: "section-heading", id: "solutions-title" },
                        "Solu\u00E7\u00F5es que conversam.",
                        React.createElement("br", null),
                        React.createElement("em", null, "Resultados que aparecem."))),
                React.createElement("p", null, "Da frente de caixa \u00E0 intelig\u00EAncia de neg\u00F3cios. Tecnologia pensada para opera\u00E7\u00F5es que n\u00E3o podem parar.")),
            React.createElement("div", { className: "solutions-grid" }, solutions.map((solution, i) => React.createElement("article", { className: `solution-card solution-card--${solution.tone} reveal`, key: solution.id, style: { '--card-delay': `${(i % 4) * 55}ms` } },
                React.createElement("div", { className: "solution-card__head" },
                    React.createElement("div", { className: "solution-card__icon" },
                        React.createElement(Icon, { name: solution.icon, size: 26 })),
                    React.createElement("span", { className: "solution-card__index" }, String(i + 1).padStart(2, '0'))),
                React.createElement("span", { className: "solution-card__category" }, solution.category),
                React.createElement("h3", null, solution.name),
                React.createElement("p", null, solution.description),
                React.createElement("div", { className: "solution-card__foot" }, solution.href ? React.createElement("a", { href: solution.href, target: "_blank", rel: "noopener noreferrer", "aria-label": `Conhecer ${solution.name} no site oficial` },
                    "Saiba mais ",
                    React.createElement(Icon, { name: "arrow-up-right", size: 17 })) : React.createElement("span", null,
                    "Parte do ecossistema VSM ",
                    React.createElement(Icon, { name: "check", size: 15 })))))),
            React.createElement("p", { className: "solutions__note" },
                "Conhe\u00E7a as solu\u00E7\u00F5es e seus detalhes atualizados no ",
                React.createElement("a", { href: "https://www.vsm.com.br/", target: "_blank", rel: "noopener noreferrer" },
                    "site oficial da VSM ",
                    React.createElement(Icon, { name: "external", size: 13 })),
                ".")));
}
