const React = window.React;
import Icon from './Icon.js';
const modules = [
    { name: 'Gestão', icon: 'database', label: 'Dados organizados', pos: 'one' },
    { name: 'Operação', icon: 'monitor', label: 'Rotina integrada', pos: 'two' },
    { name: 'B.I.', icon: 'chart', label: 'Visão estratégica', pos: 'three' },
    { name: 'Digital', icon: 'globe', label: 'Novos canais', pos: 'four' }
];
export default function Technology() {
    return React.createElement("section", { className: "technology section", id: "tecnologia", "aria-labelledby": "technology-title" },
        React.createElement("div", { className: "technology__glow", "aria-hidden": "true" }),
        React.createElement("div", { className: "container technology__layout" },
            React.createElement("div", { className: "technology__copy reveal" },
                React.createElement("p", { className: "eyebrow eyebrow--light" },
                    React.createElement("span", { className: "eyebrow__line" }),
                    " TECNOLOGIA & INTEGRA\u00C7\u00C3O"),
                React.createElement("h2", { className: "section-heading section-heading--light", id: "technology-title" },
                    "N\u00E3o s\u00E3o sistemas isolados.",
                    React.createElement("br", null),
                    React.createElement("em", null, "\u00C9 tudo conectado.")),
                React.createElement("p", null, "Quando processos e informa\u00E7\u00F5es trabalham juntos, sua opera\u00E7\u00E3o ganha uma vis\u00E3o mais clara do que realmente importa."),
                React.createElement("div", { className: "technology__points" },
                    React.createElement("div", null,
                        React.createElement("span", null,
                            React.createElement(Icon, { name: "database", size: 20 })),
                        React.createElement("div", null,
                            React.createElement("strong", null, "Informa\u00E7\u00F5es centralizadas"),
                            React.createElement("small", null, "Mais organiza\u00E7\u00E3o e consist\u00EAncia em cada etapa."))),
                    React.createElement("div", null,
                        React.createElement("span", null,
                            React.createElement(Icon, { name: "activity", size: 20 })),
                        React.createElement("div", null,
                            React.createElement("strong", null, "Rotinas conectadas"),
                            React.createElement("small", null, "Menos barreiras entre os processos do dia a dia."))),
                    React.createElement("div", null,
                        React.createElement("span", null,
                            React.createElement(Icon, { name: "chart", size: 20 })),
                        React.createElement("div", null,
                            React.createElement("strong", null, "Decis\u00F5es com contexto"),
                            React.createElement("small", null, "Indicadores que ajudam a enxergar o todo."))))),
            React.createElement("div", { className: "eco-diagram reveal", "aria-label": "Diagrama conceitual das \u00E1reas de tecnologia conectadas pela VSM" },
                React.createElement("div", { className: "eco-diagram__top" },
                    React.createElement("span", null,
                        React.createElement("span", { className: "eco-diagram__pulse" }),
                        " MAPA DE INTEGRA\u00C7\u00D5ES"),
                    React.createElement("span", null, "ILUSTRATIVO / 01")),
                React.createElement("svg", { className: "eco-diagram__lines", viewBox: "0 0 520 410", preserveAspectRatio: "none", "aria-hidden": "true" },
                    React.createElement("path", { d: "M260 205 122 93M260 205 398 93M260 205 122 320M260 205 398 320", stroke: "#466995", strokeWidth: "1.5", strokeDasharray: "5 7" }),
                    React.createElement("circle", { cx: "260", cy: "205", r: "135", fill: "none", stroke: "#24395e", strokeWidth: "1", strokeDasharray: "3 8" }),
                    React.createElement("circle", { cx: "260", cy: "205", r: "177", fill: "none", stroke: "#1e3657", strokeWidth: "1" })),
                React.createElement("div", { className: "eco-diagram__core" },
                    React.createElement("div", { className: "eco-diagram__core-icon" }, "V"),
                    React.createElement("strong", null, "ECOSSISTEMA"),
                    React.createElement("span", null, "VSM")),
                modules.map(module => React.createElement("div", { key: module.name, className: `eco-node eco-node--${module.pos}` },
                    React.createElement("span", null,
                        React.createElement(Icon, { name: module.icon, size: 19 })),
                    React.createElement("div", null,
                        React.createElement("strong", null, module.name),
                        React.createElement("small", null, module.label)))),
                React.createElement("div", { className: "eco-diagram__bottom" },
                    React.createElement("span", null,
                        React.createElement(Icon, { name: "shield", size: 14 }),
                        " Fluxos interligados"),
                    React.createElement("span", null, "CONCEITO VISUAL")))));
}
